services:
  - type: web
    name: splitwise-backend
    env: python
    buildCommand: ./build.sh
    startCommand: gunicorn config.wsgi:application --chdir backend
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.3
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
